name: GOVT-PREP CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx (for building)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t madhesh1171/govt-prep-app:latest .

      # 5️⃣ Test the Docker image (basic run test)
      - name: Test the Docker image
        run: |
          docker run -d -p 8080:80 --name test-govt-prep madhesh1171/govt-prep-app:latest
          sleep 5
          docker ps | grep test-govt-prep
          docker stop test-govt-prep

      # 6️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push madhesh1171/govt-prep-app:latest
