name: GOVT-PREP CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t madhesh1171/govt-prep-app:latest .  # <-- update path if Dockerfile not in repo root
          
      # 5️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push madhesh1171/govt-prep-app:latest

      # 6️⃣ Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.4

      # 7️⃣ Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./iac

      # 8️⃣ Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./iac
